import React from 'react';
import RiskGauge from '../components/ui/RiskGauge';
import SensorChart from '../components/ui/SensorChart';

const RiskAnalysis = ({ riskData, sensorData, lastSync }) => {
  if (!riskData) return <div>Loading...</div>;

  const { overallRisk, overallCondition, highestRiskNode, factors, decision, riskHistory } = riskData;

  const getSeverityColor = (severity) => {
    switch (severity?.toLowerCase()) {
      case 'critical': return 'bg-status-critical-bg text-status-critical';
      case 'high': return 'bg-status-critical-bg text-status-critical';
      case 'warning':
      case 'medium': return 'bg-status-warning-bg text-status-warning';
      case 'low':
      case 'safe': return 'bg-status-safe-bg text-status-safe';
      default: return 'bg-mine-surface-alt text-mine-text-secondary';
    }
  };

  const currentRiskColor = overallRisk > 75 ? '#C4362E' : overallRisk > 50 ? '#C4820E' : '#2D8A4E';

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold text-mine-text-primary">Risk Analysis</h1>
        <p className="text-mine-text-secondary text-sm mt-1">Prototype decision engine for ground stability assessment</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Current Risk */}
        <div className="card flex flex-col items-center justify-center p-6 lg:col-span-1">
          <h2 className="text-lg font-semibold text-mine-text-primary mb-6 w-full text-left">Current Risk</h2>
          <RiskGauge value={overallRisk} />
          <div className="mt-6 text-center">
            <h3 className="text-xl font-semibold text-mine-text-primary">{overallCondition}</h3>
            <p className="text-mine-text-secondary text-sm mt-1">
              Highest risk detected at node {highestRiskNode?.id || 'N/A'}
            </p>
          </div>
        </div>

        {/* Risk Timeline */}
        <div className="card p-6 lg:col-span-2">
          <h2 className="text-lg font-semibold text-mine-text-primary mb-4">Risk Timeline</h2>
          <div className="text-xs uppercase tracking-wider text-mine-text-secondary mb-2">Risk Score — Last 30 Minutes</div>
          <div className="h-48">
            <SensorChart data={riskHistory || []} dataKey="value" color={currentRiskColor} />
          </div>
        </div>

        {/* Contributing Factors */}
        <div className="card p-6 lg:col-span-1">
          <h2 className="text-lg font-semibold text-mine-text-primary mb-4">Contributing Factors</h2>
          <div className="space-y-0">
            {factors?.map((factor, idx) => (
              <div key={idx} className="flex justify-between items-center py-3 border-b border-mine-border last:border-0">
                <div className="flex flex-col">
                  <span className="text-sm font-semibold text-mine-text-primary">{factor.name}</span>
                  <span className="text-xs text-mine-text-secondary tabular-nums">{factor.raw}</span>
                </div>
                <span className={`px-2.5 py-1 text-xs font-semibold rounded-full uppercase tracking-wider ${getSeverityColor(factor.severity)}`}>
                  {factor.severity}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Model Decision */}
        <div className="card p-6 lg:col-span-1">
          <h2 className="text-lg font-semibold text-mine-text-primary mb-4">Assessment Output</h2>
          <div className="bg-mine-surface-alt border border-mine-border rounded p-4 text-mine-text-primary font-medium text-sm leading-relaxed">
            {decision}
          </div>
          <p className="text-xs text-mine-text-secondary mt-4 italic">
            Generated by rule-based prototype decision engine. Not a trained AI model.
          </p>
        </div>

        {/* Analysis Method */}
        <div className="card p-6 lg:col-span-1">
          <h2 className="text-lg font-semibold text-mine-text-primary mb-4">Analysis Method</h2>
          <ol className="list-decimal list-inside space-y-2 text-sm text-mine-text-primary">
            <li>Sensor normalization</li>
            <li>Trend analysis</li>
            <li>Anomaly detection</li>
            <li>Multi-sensor correlation</li>
            <li>Risk scoring</li>
          </ol>
        </div>

      </div>
    </div>
  );
};

export default RiskAnalysis;
